use_frameworks!

platform :ios, '9.0'

target 'JHCBaseTool_Example' do
  pod 'JHCBaseTool', :path => '../'

  target 'JHCBaseTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
